// Package inspect provides an interface to health inspection data.
package inspect

import "fmt"

// Inspection is a health inspection activity.
// Auto-generated by https://mholt.github.io/json-to-go/.
type Inspection struct {
	ActionDate           string `json:"action_date"`
	ActionSequence       string `json:"action_sequence"`
	ActionStatus         string `json:"action_status"`
	Address              string `json:"address"`
	BusinessName         string `json:"business_name"`
	City                 string `json:"city"`
	Code                 string `json:"code"`
	InspSubtype          string `json:"insp_subtype"`
	InspType             string `json:"insp_type"`
	LastTableUpdate      string `json:"last_table_update"`
	Latitude             string `json:"latitude"`
	LicenseNo            string `json:"license_no"`
	LicenseStatus        string `json:"license_status"`
	Longitude            string `json:"longitude"`
	PhoneNumber          string `json:"phone_number"`
	PostalCode           string `json:"postal_code"`
	RecordnumInsp        string `json:"recordnum_insp"`
	RecordnumLicense     string `json:"recordnum_license"`
	State                string `json:"state"`
	ViolationComments    string `json:"violation_comments"`
	ViolationDescription string `json:"violation_description"`
	ViolationKey         string `json:"violation_key"`
}

// Inspections is an array of inspections.
type Inspections []Inspection

// Summarize provides a brief summary of the given inspection.
func (i *Inspection) Summarize() string {
	const tpl string = `On %s, %s had an inspection resulting in "%s"`
	return fmt.Sprintf(tpl, i.ActionDate, i.BusinessName, i.ActionStatus)
}

// MapURL provides a URL to the location of the inspection.
func (i *Inspection) MapURL() string {
	const zoom = 17
	const tpl string = `http://www.openstreetmap.org/?mlat=%s&mlon=%s#map=%d/%s/%s`
	return fmt.Sprintf(tpl, i.Latitude, i.Longitude, zoom, i.Latitude, i.Longitude)
}
